### PR TITLE
Feature/non premium users play 30 sec preview

### PR DESCRIPTION
**Pull request by JamesRobertSutcliffe**
Preview are now playable for non-premium user but previews are not always available. Here is a summary of what I did:
  
   1 - Non-premium users can play track previews, but many tracks have null previews.
   2 - Developed functionality to show a play button only when the preview link is NOT null.
   3 - Clicking on a card opens the track/album in Spotify in a new tab.
   4 - No previews available for albums as part of their object.
   5 -Commented out playlist cards, planning to render user playlists in this container later.

Screenshot 2023-11-05 181400

**For Testing -** 
I was unsure how to write a jest test for this - maybe you could come up with a basic idea of one to write and I could attempt, only if you can be bothered.

Here are some manual tests:
1 - Check that play button functionality works
2 - Check the console data for each track and ensure if the preview url is equal to null there is no play icon
3 - Check some cards to ensure clicking on image links to external spotify site.

In regards to premium I know you cannot test this, but I have rigourously tested and the functionality is in order with the play buttons and external spotify links.

### CODE REVIEW

**Comment by patdel0** [comment]
Great job, almost there! 👍 

When I click play, nothing happens this appears and I don't get any errors.
image

Maybe this can provide some insight:
https://www.veed.io/view/6642be4b-4991-4c9a-9688-d6b7140490f1?sharingWidget=true&panel=share

**Comment by JamesRobertSutcliffe** [comment]
Hey Pat, so I cleared the confflicts but just above this comment box it is sating conflicts need to be resolved. 

I resolved the conflicts, committed the docs and then pushed up. It also looks like what I wanted pushed is now pushed to the branch with conflicts resolved, but the message below is still there and there is no option to merge to main. 

'This branch has conflicts that must be resolved
Use the [web editor](https://github.com/JamesRobertSutcliffe/personality-music-recommender/pull/76/conflicts) or the to resolve conflicts.
Conflicting files
src/app/components/personalised-homepage-components/ItemCard.tsx
src/app/personalised-homepage/page.js'

Any idea why this is? 

In regards to what these commits do:

1 - Main with your liked feature is now merrged with the work on players I did. 
2 - I haven't fixed the CSS issues, I was hoping you could take a look as I am now officially banging my head against the wall!
3 - So in order for this branch to be a success I am hoping when you test your liked features still works as previously and the played now appears when play button is clicked (this is not working in chrome as we know but it shoudl work in firefox if you have). 

Sorry for the mess!

**Comment by JamesRobertSutcliffe** [comment]
Okay so I have now merged using the web editor, please now test taking into account the following:

1 - Main with your liked feature is now merrged with the work on players I did.
2 - I haven't fixed the CSS issues, I was hoping you could take a look as I am now officially banging my head against the wall!
3 - So in order for this branch to be a success I am hoping when you test your liked features still works as previously and the played now appears when play button is clicked (this is not working in chrome as we know but it shoudl work in firefox if you have).

Also I am noticing that the app is not remembering my choice of personality type. Is it supposed to do it at this stage or do we select every time?

Cheers

**Review by patdel0 — COMMENTED** [review]
By using iframe here we have a document inside a document. It becomes tricky to change things if the `<Iframe>` component doesn't have the settings for it. It adds complexity and potentially impacts performance.

image

You mentioned previously that `<audio>` wasn't working for you. What's the reason?

```js
{!userPremium() && playTrack && (
  <audio controls class="min-w-[100vw]" key={playTrack} autoPlay>
     <source src={playTrack} type="audio/mpeg" />
  </audio>
```

Once this is implemented, we should be able to fully control the audio player's styles with the selector `audio::-webkit-media-controls-panel` and similar selectors.

**Review by patdel0 — APPROVED** [review]
I fixed the error in [b7733c9](https://github.com/JamesRobertSutcliffe/personality-music-recommender/pull/76/commits/b7733c9f96737a7b2ade139e238b9ab564fe21c3) and this PR should be ready to merge.

**Comment by JamesRobertSutcliffe** [comment]
LGTM!

**Pull request merged**
