### PR TITLE
Update docs with Recommendation System API

### LINKED ISSUE #30: Initialise the recommendation model inference endpoint
Probably best to host the model in Huggingface, preferably using Docker and FastAPI

### PR DESCRIPTION
**Pull request by patdel0**
Closes #30

---

This is a simple PR that cleans up the repository. I updated the docs and removed ml-related files, as these are now hosted on [Hugging Face](https://huggingface.co/spaces/patdel0/personality-music-recommender/tree/main).

image

## Testing
1. Add this code anywhere in the application: 
```js
fetch('https://patdel0-personality-music-recommender.hf.space/recommend?mbti_type=entj&num_of_songs=5')
  .then(data => data.json())
  .then(result => console.log(result))
```
2. Confirm the fetch request returns the recommended songs objects

### CODE REVIEW

**Comment by JamesRobertSutcliffe** [comment]
so I am getting an error message:

Screenshot 2023-09-25 193300

I have tried putting the code in like below as well as without the use effect - not sure if I am missing something. I tried researching online, people were mentioning it being a CORS issue potentially? 

Screenshot 2023-09-25 193325

**Comment by patdel0** [comment]
I'm still pulling in the results okay, although I'm not doing it within the useEffect. Looks like the issue could be tied to how we're making the fetch request.

1. What do you see when you go to this URL: https://patdel0-personality-music-recommender.hf.space/recommend?mbti_type=entj&num_of_songs=5?
2. What's the outcome when you make the fetch request outside of useEffect?

I've put together some automated tests for you to run. This should help us figure out if the problem lies in how we're making the call or if there's something else at play.

For testing, run:
1. `git pull`
2. `npm i`
3. `./scripts/server.sh`
4. `npm run test`

**Comment by JamesRobertSutcliffe** [comment]
1 - So are the URL I am seeing the JSON data in object formats
Screenshot 2023-09-26 003232

2 - When not using useffect I have noticed data is being fetched into the console within VS code although the same error message is appearing. The data is not logged in VScode console when useffect is used and the same error message appears
Screenshot 2023-09-26 003129

3 - All tests passed! 
Screenshot 2023-09-26 003819

**Comment by patdel0** [comment]
Thanks for all the info!

I added middleware to solve the CORS issue you identified.
You should now be able to use the API without Next.js crying.

**Pull request merged**
